try clearlinux with libvirt

diff --git a/.github/workflows/vagrant.yml b/.github/workflows/vagrant.yml
--- a/.github/workflows/vagrant.yml
+++ b/.github/workflows/vagrant.yml
@@ -100,28 +100,31 @@ jobs:
         uses: actions/checkout@v2
         with:
           fetch-depth: 0
-      - name: Update vagrant and virtualbox
+      - name: Install vagrant and libvirt
         run: |
           brew install vagrant
-          brew install --cask virtualbox
+          vagrant plugin install vagrant-libvirt
+          brew install libvirt
+          brew services start libvirt
       - name: Create ${{ matrix.image }}
         uses: nick-invision/retry@v2
         with:
           timeout_seconds: 1200
           max_attempts: 3
           command: |
-            vagrant destroy ${{ matrix.image }} -f || true
             vagrant up ${{ matrix.image }}
-      - name: Run Salt Netdata install state on ${{ matrix.image }}
-        run: |
-          vagrant ssh ${{ matrix.image }} -- -t "sudo salt-call state.sls netdata.install pillar='{\"check_install_type\":\"${{ matrix.check_install_type }}\"}' --retcode-passthrough"
-      - name: Run Salt Netdata uninstall state on ${{ matrix.image }}
-        run: |
-          vagrant ssh ${{ matrix.image }} -- -t "sudo salt-call state.sls netdata.uninstall pillar='{\"check_install_type\":\"${{ matrix.check_install_type }}\"}' --retcode-passthrough"
-      - name: Cleanup
-        if: always()
-        run: |
-          vagrant destroy ${{ matrix.image }} -f
+#            vagrant destroy ${{ matrix.image }} -f || true
+#            vagrant up ${{ matrix.image }}
+#      - name: Run Salt Netdata install state on ${{ matrix.image }}
+#        run: |
+#          vagrant ssh ${{ matrix.image }} -- -t "sudo salt-call state.sls netdata.install pillar='{\"check_install_type\":\"${{ matrix.check_install_type }}\"}' --retcode-passthrough"
+#      - name: Run Salt Netdata uninstall state on ${{ matrix.image }}
+#        run: |
+#          vagrant ssh ${{ matrix.image }} -- -t "sudo salt-call state.sls netdata.uninstall pillar='{\"check_install_type\":\"${{ matrix.check_install_type }}\"}' --retcode-passthrough"
+#      - name: Cleanup
+#        if: always()
+#        run: |
+#          vagrant destroy ${{ matrix.image }} -f
   test_native:
     name: Test Salt Native Install
     runs-on: macos-11.0
